---
# tasks/main.yml

- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Fail if Docker is not installed
  fail:
    msg: "Docker is not installed on this host."
  when: docker_installed.failed

- name: Check if Docker Swarm is initialized
  command: "docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'"
  register: swarm_status
  when: not docker_installed.failed

- name: Fail if Docker Swarm is not initialized
  fail:
    msg: "Docker Swarm is not initialized on this host."
  when: swarm_status.stdout != "active"

- name: Success message
  debug:
    msg: "Docker is installed and Docker Swarm is initialized."
  when: swarm_status.stdout == "active"

- name: Make sure pip is installed
  package:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - certifi==2020.6.20
    - requests==2.24.0
    - docker==4.3.1

- name: login to aws ecr
  shell: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{awsecr_name}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','aws_access_key') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','aws_secret_key') }}"
  become: true

- name: Pull Device Lifecycle Manager image from ecr
  shell: docker pull {{ image_name }}
  become: true

- name: Include task to deploy Device Lifecycle Manager
  include_tasks: "{{ ansible_os_family | lower }}-deploy.yml"