---
# tasks/main.yml

- name: assert all vars are set
  assert: 
    that: "{{ item }} != '' " 
    quiet: true
  with_items:
  - service_name
  - service_volume_name
  - supervision_volume_name
  - service_mount_path
  - supervision_mount_path
  - dlm_replicas
  - dlm_application_properties
  - dlm_version
  - aws_access_key
  - aws_secret_key

- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Fail if Docker is not installed
  fail:
    msg: "Docker is not installed on this host."
  when: docker_installed.failed

- name: Check if Docker Swarm is initialized
  command: "docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'"
  register: swarm_status

- name: Fail if Docker Swarm is not initialized
  fail:
    msg: "Docker Swarm is not initialized on this host."
  when: swarm_status.stdout != "active"

- name: Success message
  debug:
    msg: "Docker is installed and Docker Swarm is initialized."
  when: swarm_status.stdout == "active"


## Required dependencies for ansible docker modules.
- name: Make sure pip is installed
  package:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - certifi==2020.6.20
    - requests==2.24.0
    - docker==4.3.1

- name: login to aws ecr
  shell: "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{awsecr_name}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','aws_access_key') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','aws_secret_key') }}"
  become: true

- name: Pull Device Lifecycle Manager image from ecr
  shell: docker pull {{ image_name }}
  become: true

- name: Write secrets to temp internet info file
  lineinfile:
    path: "/tmp/internetInfo"
    line: "{{ item.key }}={{ item.value }}"
    regexp: "^{{ item.key | replace('.', '\\.') }}="
  with_dict: "{{ dlm_internet_secrets }}"
    

- name: Make sure docker secrets for internet info exist
  docker_secret:
    name: "maintenance.internet.authentication"
    state: present

- name: Make sure docker secrets for p12 password exist
  docker_secret:
    name: "p12.password"
    state: present

- name: Deploy the Docker Swarm service
  docker_swarm_service:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      SPRING_APPLICATION_JSON: "{{ dlm_application_properties | to_json }}"
    mode: replicated
    replicas: "{{ dlm_replicas }}"
    force_update: true
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
      monitor: 60s
      order: start-first
    mounts:
      - type: volume
        source: "{{ service_volume_name }}"
        target: "{{ service_mount_path }}"
        driver_config:
          name: local
      - type: volume
        source: "{{ supervision_volume_name }}"
        target: "{{ supervision_mount_path }}"
    secrets:
      - secret_name: "maintenance.internet.authentication"
        filename: "/tmp/internetInfo"
      - secret_name: "p12.password"
        filename: "{{ supervision_mount_path }}/p12_password"

- name: Gather info of Docker Swarm service
  docker_swarm_service_info:
    name: "{{ service_name }}"
  register: swarm_service_info_daas

- name: Debug swarm_service_info_daas
  debug:
    var: swarm_service_info_daas
